coll_compliance        = 0.00005
wrap_compliance        = 0.00001
base_attach_compliance = 0.000005

# none, grid, rotated, shifted, rotated_mirrored, random_length, random
wrap_type              = rotated
wrap_steps             = 10
wrap_param             = 15.0

wrap_type_sec          = none
wrap_steps_sec         = 6
wrap_param_sec         = 15.0

# A1625_2x2_ml_3Ls, A1625_12oz_6x4_ml_3Ls, schema1, A1625_20oz_4x3_ml_6Ls_rot
schema_folder          = A1625_2x2_ml_3Ls

mu_dynamic = 0.5

camera_xoff  = 0.0  
camera_yoff  = 0.0 
camera_zoff  = 5.0    
scale_factor = 2.0

acceleration =  20.0
deceleration = -20.0
acc_time     = 1.0
dec_time     = 1.0
still_time   = 1.0

# prefix     = sim
export_obj   = false
collect_data = false

